#pragma once

#include "Common.h"

AWAY_NAMESPACE_BEGIN

/**
 * ShaderRegisterData contains the "named" registers, generated by the compiler and to be passed on to the methods.
 */
class ShaderRegisterData
{
public:
	ShaderRegisterData();

public:
	unsigned int m_normalVarying;
	unsigned int m_tangentVarying;
	unsigned int m_bitangentVarying;
	unsigned int m_uvVarying;
	unsigned int m_secondaryUVVarying;
	unsigned int m_viewDirVarying;
	unsigned int m_shadedTarget;
	unsigned int m_globalPositionVertex;
	unsigned int m_globalPositionVarying;
	unsigned int m_localPosition;
	unsigned int m_uvInput;
	unsigned int m_secondaryUVInput;
	unsigned int m_normalInput;
	unsigned int m_tangentInput;
	unsigned int m_animatedNormal;
	unsigned int m_animatedTangent;
	unsigned int m_commons;
	unsigned int m_projectionFragment;
	unsigned int m_normalFragment;
	unsigned int m_viewDirFragment;
	unsigned int m_bitangent;
};

AWAY_NAMESPACE_END